//! Lexicon-constrained post-correction of OCR output.
//!
//! Tesseract's Sinhala model confuses a small set of similar letters systematically (ව/ච, ත/න,
//! …), especially with the Sinhala MN and Sinhala Sangam MN fonts. The corrector repairs those
//! errors without a language model:
//!
//! 1. A [`Lexicon`] of word frequencies is built from clean Unicode text (`lipi lexicon build`).
//! 2. A small table of confusion [`Rule`]s (`ocr → truth`, with the probability that the source
//!    sequence was wrong) is learned from OCR output aligned with ground truth. The Sinhala table
//!    is compiled in; see `data/si_confusions.tsv`.
//! 3. For every word that is **not** in the lexicon, candidates are generated by applying up to
//!    two rules. A candidate is accepted only when it is in the lexicon with enough frequency,
//!    when it is clearly ahead of the runner-up, and (when known) when the OCR word confidence
//!    is below a gate. Words that are in the lexicon are never changed.
//!
//! The lexicon file is plain UTF-8: a header line, then `word<TAB>count` lines sorted by
//! descending count. It is read in one pass and parsed without allocation beyond the table.

use crate::normalize::normalize;
use crate::script::{Lang, is_latin, is_sinhala, is_tamil};
use std::collections::HashMap;
use std::io::{self, BufRead, BufReader, BufWriter, Write};
use std::path::Path;

const ZWJ: char = '\u{200D}';
const ZWNJ: char = '\u{200C}';

/// Whether `c` can be part of a word of `lang`: its letters, plus the joiners Indic scripts use.
pub fn is_word_char(lang: Lang, c: char) -> bool {
    match lang {
        Lang::Si => is_sinhala(c) || c == ZWJ || c == ZWNJ,
        Lang::Ta => is_tamil(c) || c == ZWJ || c == ZWNJ,
        Lang::En => is_latin(c),
    }
}

/// Words of `lang` in `text`: maximal runs of word characters, without leading or trailing
/// joiners. Punctuation, digits and other scripts separate words.
pub fn words(lang: Lang, text: &str) -> impl Iterator<Item = &str> {
    text.split(move |c| !is_word_char(lang, c)).map(|w| w.trim_matches([ZWJ, ZWNJ])).filter(|w| !w.is_empty())
}

/// Word frequencies for one language.
#[derive(Debug, Clone, PartialEq)]
pub struct Lexicon {
    lang: Lang,
    counts: HashMap<String, u32>,
    tokens: u64,
}

impl Lexicon {
    /// First line of a lexicon file.
    pub const MAGIC: &'static str = "#lipi-lexicon 1";

    /// An empty lexicon.
    pub fn new(lang: Lang) -> Self {
        Lexicon { lang, counts: HashMap::new(), tokens: 0 }
    }

    /// Build a lexicon from text.
    pub fn from_text(lang: Lang, text: &str) -> Self {
        let mut l = Lexicon::new(lang);
        l.add_text(text);
        l
    }

    /// Language of the lexicon.
    pub fn lang(&self) -> Lang {
        self.lang
    }

    /// Count the words of `text` (after [`normalize`]). Returns the number of words added.
    pub fn add_text(&mut self, text: &str) -> usize {
        let text = normalize(text);
        let mut n = 0;
        for w in words(self.lang, &text) {
            *self.counts.entry(w.to_string()).or_insert(0) += 1;
            n += 1;
        }
        self.tokens += n as u64;
        n
    }

    /// Frequency of `word`; 0 when unknown.
    pub fn freq(&self, word: &str) -> u32 {
        self.counts.get(word).copied().unwrap_or(0)
    }

    /// Whether `word` occurs in the lexicon.
    pub fn contains(&self, word: &str) -> bool {
        self.counts.contains_key(word)
    }

    /// Number of distinct words.
    pub fn len(&self) -> usize {
        self.counts.len()
    }

    /// Whether the lexicon has no words.
    pub fn is_empty(&self) -> bool {
        self.counts.is_empty()
    }

    /// Number of words counted while building.
    pub fn tokens(&self) -> u64 {
        self.tokens
    }

    /// Drop words seen fewer than `min_count` times.
    pub fn prune(&mut self, min_count: u32) {
        self.counts.retain(|_, n| *n >= min_count);
    }

    /// Write the lexicon in its file format.
    pub fn write_to<W: Write>(&self, w: W) -> io::Result<()> {
        let mut w = BufWriter::new(w);
        writeln!(
            w,
            "{} lang={} types={} tokens={}",
            Self::MAGIC,
            self.lang.code(),
            self.counts.len(),
            self.tokens
        )?;
        let mut entries: Vec<(&String, &u32)> = self.counts.iter().collect();
        entries.sort_by(|a, b| b.1.cmp(a.1).then_with(|| a.0.cmp(b.0)));
        for (word, n) in entries {
            writeln!(w, "{word}\t{n}")?;
        }
        w.flush()
    }

    /// Save to `path`, creating parent directories.
    pub fn save(&self, path: &Path) -> io::Result<()> {
        if let Some(dir) = path.parent() {
            std::fs::create_dir_all(dir)?;
        }
        self.write_to(std::fs::File::create(path)?)
    }

    /// Read a lexicon in its file format.
    pub fn read_from<R: BufRead>(r: R) -> io::Result<Self> {
        let bad = |m: String| io::Error::new(io::ErrorKind::InvalidData, m);
        let mut lines = r.lines();
        let header = lines.next().ok_or_else(|| bad("empty lexicon file".into()))??;
        let Some(fields) = header.strip_prefix(Self::MAGIC) else {
            return Err(bad(format!("not a lipi lexicon (expected `{}`)", Self::MAGIC)));
        };
        let mut lang = None;
        let mut tokens = 0u64;
        let mut types = 0usize;
        for kv in fields.split_whitespace() {
            match kv.split_once('=') {
                Some(("lang", v)) => lang = Lang::parse(v),
                Some(("tokens", v)) => {
                    tokens = v.parse().map_err(|_| bad(format!("bad token count `{v}`")))?
                }
                Some(("types", v)) => types = v.parse().unwrap_or(0),
                _ => {}
            }
        }
        let lang = lang.ok_or_else(|| bad("lexicon header has no known `lang=`".into()))?;
        let mut counts = HashMap::with_capacity(types);
        for (i, line) in lines.enumerate() {
            let line = line?;
            if line.is_empty() || line.starts_with('#') {
                continue;
            }
            let Some((word, n)) = line.rsplit_once('\t') else {
                return Err(bad(format!("line {}: expected `word<TAB>count`", i + 2)));
            };
            let n: u32 = n.trim().parse().map_err(|_| bad(format!("line {}: bad count `{n}`", i + 2)))?;
            counts.insert(word.to_string(), n);
        }
        Ok(Lexicon { lang, counts, tokens })
    }

    /// Load from `path`.
    pub fn load(path: &Path) -> io::Result<Self> {
        Self::read_from(BufReader::new(std::fs::File::open(path)?))
    }
}

/// A confusion rule: the OCR engine wrote `from` where the text had `to`.
#[derive(Debug, Clone, PartialEq)]
pub struct Rule {
    /// Sequence the engine produced.
    pub from: Vec<char>,
    /// Sequence that was on the page.
    pub to: Vec<char>,
    /// Probability that an occurrence of `from` in OCR output should have been `to`
    /// (in `0.0..=1.0`); used to rank candidates.
    pub weight: f32,
}

impl Rule {
    /// A rule from strings.
    pub fn new(from: &str, to: &str, weight: f32) -> Self {
        Rule { from: from.chars().collect(), to: to.chars().collect(), weight }
    }
}

/// Parse a rule table: one `from<TAB>to<TAB>weight` rule per line; `#` starts a comment.
/// Malformed lines are skipped.
pub fn parse_rules(table: &str) -> Vec<Rule> {
    table
        .lines()
        .filter(|l| !l.trim().is_empty() && !l.starts_with('#'))
        .filter_map(|l| {
            let mut cols = l.split('\t');
            let from = cols.next()?;
            let to = cols.next()?;
            let weight: f32 = cols.next()?.trim().parse().ok()?;
            (!from.is_empty() && from != to).then(|| Rule::new(from, to, weight.clamp(0.0, 1.0)))
        })
        .collect()
}

/// Sinhala confusion rules learned from Tesseract output (`data/si_confusions.tsv`).
pub fn sinhala_rules() -> Vec<Rule> {
    parse_rules(include_str!("data/si_confusions.tsv"))
}

/// Acceptance thresholds for the corrector.
#[derive(Debug, Clone, Copy, PartialEq)]
pub struct Options {
    /// Maximum number of rules applied to one word.
    pub max_edits: usize,
    /// Minimum lexicon frequency of an accepted candidate.
    pub min_freq: u32,
    /// Minimum score (frequency × rule probabilities, the expected count of the error) of an
    /// accepted candidate. Keeps unlikely rule paths from reaching common words.
    pub min_score: f64,
    /// The best candidate's score must be at least this many times the runner-up's.
    pub margin: f64,
    /// Words whose OCR confidence is known and at least this high are left alone.
    /// `None` disables the gate.
    pub confidence_gate: Option<f32>,
    /// Words shorter than this (in code points) are left alone.
    pub min_len: usize,
}

impl Default for Options {
    fn default() -> Self {
        Options {
            max_edits: 2,
            min_freq: 1,
            min_score: 0.05,
            margin: 3.0,
            confidence_gate: Some(97.0),
            min_len: 3,
        }
    }
}

/// A candidate correction that is in the lexicon.
#[derive(Debug, Clone, PartialEq)]
pub struct Candidate {
    /// The candidate word.
    pub word: String,
    /// Rules applied to reach it.
    pub edits: usize,
    /// Product of the weights of the rules applied.
    pub weight: f64,
    /// Lexicon frequency.
    pub freq: u32,
}

impl Candidate {
    /// Ranking score: frequency weighted by the likelihood of the edit path.
    pub fn score(&self) -> f64 {
        f64::from(self.freq) * self.weight
    }
}

/// Upper bound on distinct variants generated for one word.
const MAX_VARIANTS: usize = 4096;

/// Corrects words with a lexicon and confusion rules.
#[derive(Debug, Clone)]
pub struct Corrector {
    lexicon: Lexicon,
    rules: Vec<Rule>,
    options: Options,
}

impl Corrector {
    /// A corrector with the compiled-in rules for the lexicon's language and default options.
    pub fn new(lexicon: Lexicon) -> Self {
        let rules = match lexicon.lang() {
            Lang::Si => sinhala_rules(),
            _ => Vec::new(),
        };
        Corrector { lexicon, rules, options: Options::default() }
    }

    /// A corrector with explicit rules and options.
    pub fn with_rules(lexicon: Lexicon, rules: Vec<Rule>, options: Options) -> Self {
        Corrector { lexicon, rules, options }
    }

    /// The lexicon.
    pub fn lexicon(&self) -> &Lexicon {
        &self.lexicon
    }

    /// The rules.
    pub fn rules(&self) -> &[Rule] {
        &self.rules
    }

    /// The options.
    pub fn options(&self) -> Options {
        self.options
    }

    /// Replace the options.
    pub fn set_options(&mut self, options: Options) {
        self.options = options;
    }

    /// Every distinct form reachable from `word` by applying at most `max_edits` rules, with
    /// the number of edits and the best weight product. Not filtered by the lexicon.
    pub fn variants(&self, word: &str) -> Vec<(String, usize, f64)> {
        let original: Vec<char> = word.chars().collect();
        let mut seen: HashMap<String, (usize, f64)> = HashMap::new();
        let mut frontier: Vec<(Vec<char>, f64)> = vec![(original.clone(), 1.0)];
        for depth in 1..=self.options.max_edits {
            let mut next = Vec::new();
            for (w, weight) in &frontier {
                for rule in &self.rules {
                    let n = rule.from.len();
                    if n == 0 || w.len() < n {
                        continue;
                    }
                    for i in 0..=w.len() - n {
                        if w[i..i + n] != rule.from[..] {
                            continue;
                        }
                        let mut v = Vec::with_capacity(w.len() + rule.to.len());
                        v.extend_from_slice(&w[..i]);
                        v.extend_from_slice(&rule.to);
                        v.extend_from_slice(&w[i + n..]);
                        if v == original {
                            continue;
                        }
                        let s: String = v.iter().collect();
                        let score = weight * f64::from(rule.weight);
                        let better = seen.get(&s).is_none_or(|&(_, old)| score > old);
                        if better && (seen.contains_key(&s) || seen.len() < MAX_VARIANTS) {
                            seen.insert(s, (depth, score));
                            next.push((v, score));
                        }
                    }
                }
            }
            frontier = next;
        }
        seen.into_iter().map(|(s, (d, w))| (s, d, w)).collect()
    }

    /// Variants of `word` that are in the lexicon, best score first.
    pub fn candidates(&self, word: &str) -> Vec<Candidate> {
        let mut v: Vec<Candidate> = self
            .variants(word)
            .into_iter()
            .filter_map(|(w, edits, weight)| {
                let freq = self.lexicon.freq(&w);
                (freq > 0).then_some(Candidate { word: w, edits, weight, freq })
            })
            .collect();
        v.sort_by(|a, b| b.score().total_cmp(&a.score()).then_with(|| a.word.cmp(&b.word)));
        v
    }

    /// The correction for `word`, if one is accepted. `confidence` is the OCR word confidence
    /// (0-100) when known.
    pub fn correct_word(&self, word: &str, confidence: Option<f32>) -> Option<String> {
        let o = &self.options;
        if word.chars().count() < o.min_len || self.lexicon.contains(word) {
            return None;
        }
        if let (Some(gate), Some(c)) = (o.confidence_gate, confidence)
            && c >= gate
        {
            return None;
        }
        let cands = self.candidates(word);
        let best = cands.first()?;
        if best.freq < o.min_freq || best.score() < o.min_score {
            return None;
        }
        if let Some(second) = cands.get(1)
            && best.score() < o.margin * second.score()
        {
            return None;
        }
        Some(best.word.clone())
    }

    /// Correct every word of the lexicon's language in `text`, keeping everything else
    /// (whitespace, punctuation, other scripts) as it is. `confidence` maps a whitespace-separated
    /// token to its OCR confidence when known. Returns the text and the number of words changed.
    pub fn correct_text(&self, text: &str, confidence: &dyn Fn(&str) -> Option<f32>) -> (String, usize) {
        let mut out = String::with_capacity(text.len());
        let mut changed = 0;
        let mut rest = text;
        while !rest.is_empty() {
            let token_start = rest.find(|c: char| !c.is_whitespace()).unwrap_or(rest.len());
            out.push_str(&rest[..token_start]);
            rest = &rest[token_start..];
            if rest.is_empty() {
                break;
            }
            let token_end = rest.find(char::is_whitespace).unwrap_or(rest.len());
            let token = &rest[..token_end];
            self.correct_token(token, confidence(token), &mut out, &mut changed);
            rest = &rest[token_end..];
        }
        (out, changed)
    }

    fn correct_token(&self, token: &str, confidence: Option<f32>, out: &mut String, changed: &mut usize) {
        let lang = self.lexicon.lang;
        let mut word_start: Option<usize> = None;
        let mut flush = |word: &str, out: &mut String| {
            let core = word.trim_matches([ZWJ, ZWNJ]);
            match self.correct_word(core, confidence) {
                Some(fixed) if !core.is_empty() => {
                    let lead = &word[..word.len() - word.trim_start_matches([ZWJ, ZWNJ]).len()];
                    let trail = &word[word.trim_end_matches([ZWJ, ZWNJ]).len()..];
                    out.push_str(lead);
                    out.push_str(&fixed);
                    out.push_str(trail);
                    *changed += 1;
                }
                _ => out.push_str(word),
            }
        };
        for (i, c) in token.char_indices() {
            if is_word_char(lang, c) {
                word_start.get_or_insert(i);
            } else {
                if let Some(s) = word_start.take() {
                    flush(&token[s..i], out);
                }
                out.push(c);
            }
        }
        if let Some(s) = word_start {
            flush(&token[s..], out);
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn lexicon() -> Lexicon {
        let mut l = Lexicon::new(Lang::Si);
        for (w, n) in [("විජිත", 5), ("තීන්දුව", 8), ("පත්", 20), ("කිරීම", 50), ("වල", 100), ("බල", 9), ("සල", 1)]
        {
            for _ in 0..n {
                l.add_text(w);
            }
        }
        l
    }

    fn rules() -> Vec<Rule> {
        vec![
            Rule::new("ච", "ව", 0.3),
            Rule::new("න", "ත", 0.2),
            Rule::new("ච", "බ", 0.1),
            Rule::new("ච", "ස", 0.1),
        ]
    }

    fn corrector(options: Options) -> Corrector {
        Corrector::with_rules(lexicon(), rules(), options)
    }

    #[test]
    fn splits_words_of_a_script() {
        let v: Vec<&str> = words(Lang::Si, "ශ්‍රී ලංකා, 2024-05-15 දිනැති (Cabinet) තීන්දුව.").collect();
        assert_eq!(v, ["ශ්‍රී", "ලංකා", "දිනැති", "තීන්දුව"]);
        assert_eq!(words(Lang::Ta, "இலங்கை si").collect::<Vec<_>>(), ["இலங்கை"]);
    }

    #[test]
    fn generates_variants_within_two_edits() {
        let c = corrector(Options::default());
        let v = c.variants("චිජිත");
        assert!(v.iter().any(|(w, d, _)| w == "විජිත" && *d == 1));
        assert!(v.iter().any(|(w, _, _)| w == "බිජිත"));
        assert!(!v.iter().any(|(w, _, _)| w == "චිජිත"));
        // two edits: ච→ව and න→ත
        let v = c.variants("නීන්දුච");
        let hit = v.iter().find(|(w, _, _)| w == "තීන්දුව").expect("reachable");
        assert_eq!(hit.1, 2);
        assert!((hit.2 - 0.06).abs() < 1e-6);
    }

    #[test]
    fn accepts_clear_lexicon_candidates() {
        let c = corrector(Options::default());
        assert_eq!(c.correct_word("චිජිත", None).as_deref(), Some("විජිත"));
        assert_eq!(c.correct_word("නීන්දුච", None).as_deref(), Some("තීන්දුව"));
        assert_eq!(c.correct_word("පන්", None).as_deref(), Some("පත්"));
    }

    #[test]
    fn never_changes_known_words_or_short_ones() {
        let c = corrector(Options::default());
        assert_eq!(c.correct_word("විජිත", None), None);
        assert_eq!(c.correct_word("පත්", None), None);
        assert_eq!(c.correct_word("චල", None), None); // below min_len
        assert_eq!(c.correct_word("චිජිතයා", None), None); // no candidate in the lexicon
    }

    #[test]
    fn rejects_ambiguous_and_rare_candidates() {
        let mut o = Options { min_len: 2, ..Options::default() };
        // "වල" (100 × 0.3 = 30) vs "බල" (9 × 0.1 = 0.9): clear.
        let c = corrector(o);
        assert_eq!(c.correct_word("චල", None).as_deref(), Some("වල"));
        // With a huge margin the runner-up blocks the correction.
        o.margin = 100.0;
        assert_eq!(corrector(o).correct_word("චල", None), None);
        // "සල" occurs once: below min_freq 2, and below min_score when the rule is unlikely.
        let rule = vec![Rule::new("ච", "ස", 0.5)];
        let o = Options { min_len: 2, min_freq: 2, ..Options::default() };
        assert_eq!(Corrector::with_rules(lexicon(), rule.clone(), o).correct_word("චල", None), None);
        let o = Options { min_len: 2, ..Options::default() };
        assert_eq!(Corrector::with_rules(lexicon(), rule, o).correct_word("චල", None).as_deref(), Some("සල"));
        let o = Options { min_len: 2, min_score: 0.05, ..Options::default() };
        let c = Corrector::with_rules(lexicon(), vec![Rule::new("ච", "ස", 0.01)], o);
        assert_eq!(c.correct_word("චල", None), None, "1 × 0.01 is below min_score");
    }

    #[test]
    fn confidence_gate_protects_confident_words() {
        let c = corrector(Options { confidence_gate: Some(90.0), ..Options::default() });
        assert_eq!(c.correct_word("චිජිත", Some(95.0)), None);
        assert_eq!(c.correct_word("චිජිත", Some(60.0)).as_deref(), Some("විජිත"));
        assert_eq!(c.correct_word("චිජිත", None).as_deref(), Some("විජිත"));
        let c = corrector(Options { confidence_gate: None, ..Options::default() });
        assert_eq!(c.correct_word("චිජිත", Some(99.0)).as_deref(), Some("විජිත"));
    }

    #[test]
    fn corrects_text_in_place() {
        let c = corrector(Options::default());
        let (text, n) = c.correct_text("චිජිත, පන්\n  (කිරීම) 2024 නීන්දුච.", &|_| None);
        assert_eq!(text, "විජිත, පත්\n  (කිරීම) 2024 තීන්දුව.");
        assert_eq!(n, 3);
        let conf = |t: &str| (t == "චිජිත,").then_some(99.0);
        let c = corrector(Options { confidence_gate: Some(90.0), ..Options::default() });
        let (text, n) = c.correct_text("චිජිත, පන්", &conf);
        assert_eq!((text.as_str(), n), ("චිජිත, පත්", 1));
    }

    #[test]
    fn parses_rule_tables() {
        let r = parse_rules("# comment\nච\tව\t0.31\n\nබ\tබ\t1\nx\ty\n්ර\t්\u{200D}ර\t0.5\n");
        assert_eq!(r.len(), 2);
        assert_eq!(r[0], Rule::new("ච", "ව", 0.31));
        assert_eq!(r[1].to, vec!['්', '\u{200D}', 'ර']);
        assert!(!sinhala_rules().is_empty());
    }

    #[test]
    fn lexicon_round_trip() {
        let l = lexicon();
        let mut buf = Vec::new();
        l.write_to(&mut buf).unwrap();
        let text = String::from_utf8(buf).unwrap();
        assert!(text.starts_with("#lipi-lexicon 1 lang=si types=7 tokens=193\n"));
        assert!(text.lines().nth(1).unwrap().starts_with("වල\t100"));
        let back = Lexicon::read_from(text.as_bytes()).unwrap();
        assert_eq!(back, l);
        assert!(Lexicon::read_from("nonsense\n".as_bytes()).is_err());
    }
}
