//! FM Abhaya code table.
//!
//! FM Abhaya, FM Abhaya x and FM Ababld (the bold face) share one encoding; they are the
//! legacy fonts of Sri Lankan government gazettes and acts typeset before Unicode. The table
//! maps a code sequence, as it appears in a PDF text layer decoded with the font's
//! WinAnsi encoding, to Unicode Sinhala in the font's own *visual* order
//! ([`super::Converter`] reorders the pre-base signs afterwards).
//!
//! # Derivation
//!
//! The table was derived from 19,338 word pairs on 91 gazette pages: the legacy word from the
//! text layer, paired by bounding box with Tesseract's reading of the rendered page, then
//! aligned with a monotone Viterbi-EM model over code sequences (`bench/legacy/derive.py`).
//! Entries whose majority reading was an OCR error were corrected by reading the paired words
//! (`±` is දැ, not දු; `ø` carries the rakaransaya of මුද්‍රණ; `ð` is ජි as in සාමාජික;
//! `Æ` is ලූ; `×` is ඥා; the quote codes `z`/`Z` and `—`/`˜` are typographic quotes). A few
//! two-code compositions that follow from Sinhala orthography were added without a corpus
//! occurrence (`Ta` → ඕ, `T!` → ඖ, `` `v `` → ඬ), and `DD` → ෲ from a held-out page (බෲනායි). Codes that never occurred in the corpus
//! (`F`, `J`, `R`, `V`, `X`, `]`, `_`, `}`, `#`, `?`) are left unmapped and pass through.
//!
//! Multi-code entries are either ligature glyphs typed as several codes (`ff` → ෛ, `zz` → “),
//! independent vowels composed of two glyphs (`wd` → ආ, `we` → ඇ, `wE` → ඈ, `ta` → ඒ) or the
//! context form of a vowel sign (`re` → රු, `rE` → රූ: after ර the ැ/ෑ codes draw ු/ූ).

/// Family identifier shared by FM Abhaya, FM Abhaya x and FM Ababld (bold).
pub const FAMILY: &str = "fm-abhaya";

/// Code sequence to Unicode (visual order), sorted by code sequence.
pub const TABLE: &[(&str, &str)] = &[
    ("!", "ෟ"),
    ("\"", ","),
    ("$", "/"),
    ("%", "්\u{200D}ර"),
    ("&", ")"),
    ("'", "."),
    ("(", ":"),
    ("*", "ෆ"),
    ("+", "ූ"),
    (",", "ල"),
    ("-", "-"),
    (".", "ග"),
    ("/", "රැ"),
    ("0", "0"),
    ("1", "1"),
    ("2", "2"),
    ("3", "3"),
    ("4", "4"),
    ("5", "5"),
    ("6", "6"),
    ("7", "7"),
    ("8", "8"),
    ("9", "9"),
    (":", "ථ"),
    (";", "ත"),
    ("<", "ළ"),
    ("=", "ු"),
    (">", "ඝ"),
    ("@", "?"),
    ("A", "්"),
    ("B", "ඊ"),
    ("C", "ක්\u{200D}"),
    ("D", "ෘ"),
    ("DD", "ෲ"),
    ("E", "ෑ"),
    ("G", "ඨ"),
    ("H", "්\u{200D}ය"),
    ("I", "ෂ"),
    ("K", "ණ"),
    ("L", "ඛ"),
    ("M", "ඵ"),
    ("N", "භ"),
    ("O", "ධ"),
    ("P", "ඡ"),
    ("Q", "ූ"),
    ("S", "ී"),
    ("T", "ඔ"),
    ("T!", "ඖ"),
    ("TA", "ඕ"),
    ("Ta", "ඕ"),
    ("U", "ඹ"),
    ("W", "උ"),
    ("Y", "ශ"),
    ("Z", "\u{2019}"),
    ("ZZ", "\u{201D}"),
    ("[", "ඤ"),
    ("^", "("),
    ("`.", "ඟ"),
    ("`o", "ඳ"),
    ("`v", "ඬ"),
    ("a", "්"),
    ("b", "ඉ"),
    ("c", "ජ"),
    ("d", "ා"),
    ("e", "ැ"),
    ("f", "ෙ"),
    ("g", "ට"),
    ("h", "ය"),
    ("i", "ස"),
    ("j", "ව"),
    ("k", "න"),
    ("l", "ක"),
    ("m", "ප"),
    ("n", "බ"),
    ("o", "ද"),
    ("p", "ච"),
    ("q", "ු"),
    ("r", "ර"),
    ("rE", "රූ"),
    ("re", "රු"),
    ("s", "ි"),
    ("t", "එ"),
    ("tA", "ඒ"),
    ("ta", "ඒ"),
    ("u", "ම"),
    ("v", "ඩ"),
    ("w", "අ"),
    ("wE", "ඈ"),
    ("wd", "ආ"),
    ("we", "ඇ"),
    ("x", "ං"),
    ("y", "හ"),
    ("z", "\u{2018}"),
    ("zz", "\u{201C}"),
    ("{", "ඥ"),
    ("|", "ඳ"),
    ("~", "ඬ"),
    ("\u{00A1}", "."),
    ("\u{00A2}", "ඳි"),
    ("\u{00A5}", "දූ"),
    ("\u{00A6}", ";"),
    ("\u{00A7}", "දී"),
    ("\u{00A8}", "ලු"),
    ("\u{00B1}", "දැ"),
    ("\u{00B4}", "ඕ"),
    ("\u{00BE}", "ර්"),
    ("\u{00BF}", "ළු"),
    ("\u{00C5}", "ඛි"),
    ("\u{00C6}", "ලූ"),
    ("\u{00C8}", "දි"),
    ("\u{00C9}", "ච්"),
    ("\u{00CA}", "ජ්"),
    ("\u{00CB}", "ක්\u{200D}ෂ"),
    ("\u{00CD}", "රී"),
    ("\u{00D1}", "චි"),
    ("\u{00D1}s", "චි"),
    ("\u{00D3}", "ථි"),
    ("\u{00D4}", "ජී"),
    ("\u{00D5}", "ඟ"),
    ("\u{00D6}", "චී"),
    ("\u{00D7}", "ඥා"),
    ("\u{00DC}", "ට්"),
    ("\u{00DE}", "දා"),
    ("\u{00DF}", "රි"),
    ("\u{00E0}", "ටී"),
    ("\u{00E1}", "ටි"),
    ("\u{00E2}", "ඩ්"),
    ("\u{00E3}", "ඩී"),
    ("\u{00E4}", "ඩි"),
    ("\u{00EA}", "ධි"),
    ("\u{00EB}", "ධී"),
    ("\u{00EC}", "බි"),
    ("\u{00ED}", "බ්"),
    ("\u{00EE}", "බී"),
    ("\u{00EF}", "ම්"),
    ("\u{00F0}", "ජි"),
    ("\u{00F1}", "මි"),
    ("\u{00F3}", "මී"),
    ("\u{00F5}", "ව්"),
    ("\u{00F7}", "ඳු"),
    ("\u{00F8}", "ද්\u{200D}ර"),
    ("\u{00F9}", "වී"),
    ("\u{00FA}", "වි"),
    ("\u{00FD}", "ඡි"),
    ("\u{00FE}", "ඡ"),
    ("\u{00FF}", "දු"),
    ("\u{0152}", "ණී"),
    ("\u{02DC}", "\u{201D}"),
    ("\u{2014}", "\u{201C}"),
    ("\u{201A}", "ණි"),
    ("\u{203A}", "ශ්\u{200D}රී"),
];
